package org.tur

import android.content.Context
import android.view.Surface

/**
 * JNI bridge to the native tur engine standard operations.
 *
 * Every method is a thin `external fun` over the `Java_org_tur_TurNative_*`
 * entry points that the embedder's `.so` exports (generated by
 * `tur_android::standard_jni_exports!()` in `libs/tur-android`). They are
 * **handle-based and stateless**, so the same object safely drives any number
 * of engine instances — one per [TurView] in a multi-view app.
 *
 * This object does **not** load any library and does **not** create engines.
 * The embedder (the app) is responsible for:
 *  1. loading its `.so` (`System.loadLibrary(…)`), and
 *  2. calling its own `createEngine(…)` JNI function to obtain an opaque
 *     `Long` handle,
 *
 * then handing that handle to [TurEngine]. The handle is passed back to every
 * method here. `0` means the engine was never created (or has been destroyed);
 * the [TurEngine] wrapper guards against calling into a dead handle.
 */
object TurNative {
    /** Evaluate [js] as an ES module (`import … from "tur:*"` resolved by the engine). */
    external fun loadModule(handle: Long, js: String)

    /** Fire one engine wake — call each Choreographer / Handler tick. */
    external fun pump(handle: Long): Int

    /** Push a new surface size (logical px + dpr). */
    external fun resize(handle: Long, width: Int, height: Int, dpr: Double)

    /**
     * Push a pointer event. [action] matches `MotionEvent.ACTION_*`:
     * `0=DOWN`, `1=UP`, `2=MOVE`, `3=CANCEL`. Coordinates are logical px
     * relative to the surface; [timeMs] is `SystemClock.uptimeMillis()`.
     */
    external fun pushPointer(handle: Long, action: Int, x: Double, y: Double, timeMs: Long)

    /**
     * Push a key event. [action] is `0=DOWN`, `1=UP`. [key]/[code] are
     * browser-style strings (see [InputMapper] for the Android→browser map).
     */
    external fun pushKey(
        handle: Long,
        key: String,
        code: String,
        action: Int,
        ctrl: Boolean,
        shift: Boolean,
        alt: Boolean,
        meta: Boolean,
    )

    /**
     * Whether the currently-focused element is an editable text field. The
     * embedder polls this after each pump to decide whether to raise the soft
     * keyboard (and hide it when it flips back to false).
     */
    external fun focusedIsEditable(handle: Long): Boolean

    /**
     * Push an IME composition event. [kind]: `0=CompositionStart`,
     * `1=CompositionUpdate { text }`, `2=CompositionEnd { text }`. Used by the
     * embedder's [android.view.inputmethod.InputConnection] to deliver
     * multi-char commits / composing text (paste, autocorrect, CJK) that can't
     * be represented as a single key event.
     */
    external fun pushIme(handle: Long, kind: Int, text: String)

    /** Drop the engine and free its resources. */
    external fun destroy(handle: Long)
}
