package org.tur

import android.content.Context
import android.view.Surface

/**
 * JNI bridge to the native tur engine standard operations.
 *
 * Every method is a thin `external fun` over the `Java_org_tur_TurNative_*`
 * entry points that the embedder's `.so` exports (generated by
 * `tur_android::standard_jni_exports!()` in `libs/tur-android`). They are
 * **handle-based and stateless**, so the same object safely drives any number
 * of instances — one per [TurView] in a multi-view app — all sharing one
 * runtime.
 *
 * This object does **not** load any library and does **not** create runtimes.
 * The embedder (the app) is responsible for:
 *  1. loading its `.so` (`System.loadLibrary(…)`), and
 *  2. calling its own `createRuntime(…)` JNI function to obtain an opaque
 *     runtime `Long` handle,
 *
 * then handing that handle to [TurRuntime]. From the runtime, instances are
 * created via [createInstance] / [createHeadlessInstance] below. `0` means
 * never-created (or destroyed); the [TurRuntime] / [TurInstance] wrappers guard
 * against calling into a dead handle.
 */
object TurNative {
    /**
     * Spawn an isolated rendering instance attached to [surface], sharing the
     * runtime's fonts/clock/capabilities/wgpu-instance. Returns an opaque
     * instance handle, or `0` on failure.
     */
    external fun createInstance(
        runtimeHandle: Long,
        surface: Surface,
        width: Int,
        height: Int,
        dpr: Double,
        frameLoop: FrameLoop,
    ): Long

    /**
     * Spawn an isolated headless instance (no surface, no rendering) from the
     * runtime. Runs JS + capabilities + events only. Returns an opaque instance
     * handle, or `0` on failure.
     */
    external fun createHeadlessInstance(
        runtimeHandle: Long,
        frameLoop: FrameLoop,
    ): Long

    /** Evaluate [js] as an ES module (`import … from "tur:*"` resolved by the engine). */
    external fun loadModule(handle: Long, js: String)

    /** Fire one engine wake — call each Choreographer / Handler tick. */
    external fun pump(handle: Long): Int

    /**
     * Poll the engine's main loop WITHOUT firing a vsync — the coalesced
     * message-pump path (worker→main messages / main-loop tasks while the
     * engine is idle). Keeps an idle instance from ping-ponging at display
     * refresh rate.
     */
    external fun pumpMessages(handle: Long): Int

    /** Push a new surface size (logical px + dpr). */
    external fun resize(handle: Long, width: Int, height: Int, dpr: Double)

    /**
     * Push a pointer event. [action] matches `MotionEvent.ACTION_*`:
     * `0=DOWN`, `1=UP`, `2=MOVE`, `3=CANCEL`. Coordinates are logical px
     * relative to the surface; [timeMs] is `SystemClock.uptimeMillis()`.
     */
    external fun pushPointer(handle: Long, action: Int, x: Double, y: Double, timeMs: Long)

    /**
     * Push a key event. [action] is `0=DOWN`, `1=UP`. [key]/[code] are
     * browser-style strings (see [InputMapper] for the Android→browser map).
     */
    external fun pushKey(
        handle: Long,
        key: String,
        code: String,
        action: Int,
        ctrl: Boolean,
        shift: Boolean,
        alt: Boolean,
        meta: Boolean,
    )

    /**
     * Push an IME composition event. [kind]: `0=CompositionStart`,
     * `1=CompositionUpdate { text }`, `2=CompositionEnd { text }`. Used by the
     * embedder's [android.view.inputmethod.InputConnection] to deliver
     * multi-char commits / composing text (paste, autocorrect, CJK) that can't
     * be represented as a single key event.
     */
    external fun pushIme(handle: Long, kind: Int, text: String)

    /** Drop an instance and free its resources (the runtime is unaffected). */
    external fun destroy(handle: Long)

    /** Drop the runtime and free its resources. Destroy all instances first. */
    external fun destroyRuntime(handle: Long)
}
