package org.tur

import android.content.Context
import android.view.Surface

/**
 * JNI bridge to the native tur engine standard operations.
 *
 * Every method is a thin `external fun` over the `Java_org_tur_TurNative_*`
 * entry points that the embedder's `.so` exports (generated by
 * `tur_android::standard_jni_exports!()` in `libs/tur-android`). They are
 * **handle-based and stateless**, so the same object safely drives any number
 * of instances — one per [TurView] in a multi-view app — all sharing one
 * runtime.
 *
 * **Threading**: every op is marshalled onto the native **tur-host thread**
 * — the single thread that owns the runtime, instances, and renderers — so
 * these functions may be called from any thread (in practice: the main
 * looper, where surface + input callbacks arrive) and never run engine work
 * on the caller. Fire-and-forget ops return immediately; the op queue is
 * FIFO, so ordering is preserved. A native build failure inside a posted op
 * (e.g. wgpu init) surfaces as a logcat error and later ops for that handle
 * become no-ops.
 *
 * This object does **not** load any library and does **not** create runtimes.
 * The embedder (the app) is responsible for:
 *  1. loading its `.so` (`System.loadLibrary(…)`), and
 *  2. calling its own `createRuntime(…)` JNI function to obtain an opaque
 *     runtime `Long` handle,
 *
 * then handing that handle to [TurRuntime]. From the runtime, instances are
 * created via [createInstance] below (`0` means never-created or destroyed;
 * the [TurRuntime] / [TurInstance] wrappers guard against calling into a
 * dead handle).
 */
object TurNative {
    /**
     * Spawn an isolated engine instance — the **initialize** half of the
     * two-phase lifecycle. No surface yet: the native build (worker
     * handshake + plugin registration) is queued onto the native tur-host
     * thread while the caller stays free; ops for this handle are ordered
     * behind it. Attach a surface later via [attachInstance] (from
     * `surfaceCreated`). A build failure logs to logcat (no exception) and
     * turns later ops into no-ops. Returns `0` only for an invalid runtime
     * handle or if the host thread is gone.
     */
    external fun createInstance(
        runtimeHandle: Long,
        frameLoop: FrameLoop,
    ): Long

    /**
     * Attach a rendering surface to a built instance — the **attach** half
     * of the two-phase lifecycle (call from `surfaceCreated`, where the
     * surface is guaranteed valid). The attach op is ordered behind the
     * instance build, so the instance exists when it runs: it acquires the
     * native window, performs the wgpu surface/adapter/device init, and
     * hands the renderer to the engine. If the instance is already gone
     * (destroyed / failed build) or the wgpu init fails, the error is
     * logged and the instance stays renderer-less — attachable again
     * later. Pair with [detachInstance] on `surfaceDestroyed`; the pair is
     * repeatable (a re-created surface re-attaches without rebuilding the
     * JS realm).
     */
    external fun attachInstance(
        handle: Long,
        surface: Surface,
        width: Int,
        height: Int,
        dpr: Double,
    )

    /**
     * Detach the rendering surface — the **detach** half (call from
     * `surfaceDestroyed`). Drops the renderer and releases the native
     * window reference; the instance keeps running (JS, capabilities,
     * events) and can attach a fresh surface later. Idempotent.
     */
    external fun detachInstance(handle: Long)

    /**
     * Register a JS module source on the runtime's shared registry and return
     * an opaque source handle (`0` on failure). The source crosses JNI exactly
     * once, here; [loadModule] then loads it into any instance of the runtime
     * by handle — no per-load string copies.
     *
     * Rust-side embedders can skip this hop entirely (read the source
     * natively, e.g. an APK asset, and register it from Rust) — see the demo
     * app's `createAssetModuleSource`.
     */
    external fun registerModuleSource(runtimeHandle: Long, js: String): Long

    /**
     * Drop a registered module source. Idempotent — a stale/unknown handle is
     * a no-op. Everything left registered is freed when the runtime is
     * destroyed.
     */
    external fun releaseModuleSource(runtimeHandle: Long, sourceHandle: Long)

    /**
     * Evaluate the registered module source ([registerModuleSource]'s return
     * value) as an ES module (`import … from "tur:*"` resolved by the engine).
     * The shared source flows to the engine by refcount — zero JNI string
     * traffic. Posted onto the native tur-host thread (ordered behind the
     * instance build); a failed load logs to logcat.
     */
    external fun loadModule(handle: Long, sourceHandle: Long)

    /**
     * Fire one engine wake — call each Choreographer / Handler tick. Posts
     * the vsync pump onto the native tur-host thread (which fires the vsync
     * event, polls the loop, and applies the frame's render batch to the
     * GPU); the calling thread returns immediately.
     */
    external fun pump(handle: Long): Int

    /**
     * Poll the engine's loop WITHOUT firing a vsync — posted onto the
     * native tur-host thread (the coalesced message-pump path for
     * worker→host messages / host-loop tasks while the engine is idle).
     * Keeps an idle instance from ping-ponging at display refresh rate.
     */
    external fun pumpMessages(handle: Long): Int

    /** Push a new surface size (logical px + dpr). */
    external fun resize(handle: Long, width: Int, height: Int, dpr: Double)

    /**
     * Push a pointer event. [action] matches `MotionEvent.ACTION_*`:
     * `0=DOWN`, `1=UP`, `2=MOVE`, `3=CANCEL`. Coordinates are logical px
     * relative to the surface; [timeMs] is `SystemClock.uptimeMillis()`.
     */
    external fun pushPointer(handle: Long, action: Int, x: Double, y: Double, timeMs: Long)

    /**
     * Push a key event. [action] is `0=DOWN`, `1=UP`. [key]/[code] are
     * browser-style strings (see [InputMapper] for the Android→browser map).
     */
    external fun pushKey(
        handle: Long,
        key: String,
        code: String,
        action: Int,
        ctrl: Boolean,
        shift: Boolean,
        alt: Boolean,
        meta: Boolean,
    )

    /**
     * Push an IME composition event. [kind]: `0=CompositionStart`,
     * `1=CompositionUpdate { text }`, `2=CompositionEnd { text }`. Used by the
     * embedder's [android.view.inputmethod.InputConnection] to deliver
     * multi-char commits / composing text (paste, autocorrect, CJK) that can't
     * be represented as a single key event.
     */
    external fun pushIme(handle: Long, kind: Int, text: String)

    /**
     * Drop an instance and free its resources (the runtime is unaffected).
     *
     * Fire-and-forget: the destroy op is queued on the native tur-host
     * thread (FIFO behind anything already posted). A destroy racing the
     * instance build is harmless — the build creates no surface, so
     * whichever op runs second simply finds nothing. Dispose of a young
     * instance freely.
     */
    external fun destroy(handle: Long)

    /**
     * Drop an instance and **block until its teardown settled** on the
     * native tur-host thread: the destroy op ran, and with it the
     * instance's renderer, surface, and loop future were dropped (the
     * worker lane winds down asynchronously, running the loaded module's
     * cleanup). Returns `true` when settled, `false` if the host thread had
     * already shut down.
     *
     * The fence for hosts that must know disposal finished — e.g. before
     * re-creating an instance on the same surface — replacing sleep-based
     * quiesce heuristics. **Blocking** (it waits behind any ops still
     * queued for the instance, including an in-flight build): call off the
     * main thread, e.g. `withContext(Dispatchers.Default) {
     * TurNative.destroySettled(handle) }`.
     */
    external fun destroySettled(handle: Long): Boolean

    /** Drop the runtime and free its resources. Destroy all instances first. */
    external fun destroyRuntime(handle: Long)
}
