[package]
name = "tur-shared"
description = "Shared types for tur, with TypeScript generation via ts-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
num-derive = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
ts-rs = "12"
