[package]
name = "tur-integration-tests"
description = "Integration tests for tur element tree via JS bundles"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tur-engine = { workspace = true, features = ["wgpu-backend", "trace"] }
tur-std = { workspace = true }
tur-animation = { workspace = true }
tur-clipboard-capability = { workspace = true }
tur-net-capability = { workspace = true }
tur-native = { workspace = true }
tur-shared = { workspace = true }
boa_engine = { workspace = true }
libc = "0.2"

[dev-dependencies]
minifb = "0.28"
pollster = "0.4"
raw-window-handle = "0.6"
thiserror = { workspace = true }
wgpu = { workspace = true }

[[test]]
name = "vello"
path = "tests/vello/main.rs"
harness = false
