# Consumer ProGuard rules for the tur Compose integration.
#
# The JNI bridge (TurNative) declares `external fun`s that are resolved by name
# against `Java_org_tur_TurNative_*` symbols in the app's `.so` (e.g.
# libtur_demo.so — generated by `tur_android::standard_jni_exports!`). Keep the
# bridge object, the FrameLoop (passed across JNI as a jobject), and the
# `external` method signatures so the native side can always find them. The app
# must additionally keep its own `createRuntime`-declaring class (e.g.
# `org.tur.demo.DemoNative`).

-keep class org.tur.TurNative { *; }
-keep class org.tur.FrameLoop { *; }
-keep class org.tur.TurRuntime { *; }
-keep class org.tur.TurInstance { *; }

# Keep the native method signatures (the `Java_…` symbol names depend on the
# Kotlin method names + parameter types being unchanged).
-keepclasseswithmembernames class * {
    native <methods>;
}
