[package]
name = "tur-boajs"
description = "boa_engine JS bridge for tur element tree manipulation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tur-element-tree = { workspace = true }
tur-render-tree = { workspace = true }
boa_engine = { workspace = true }
boa_gc = { workspace = true }
num-traits = { workspace = true }
tracing = { workspace = true }
