package org.tur.demo

import android.content.Context
import android.view.Surface
import org.tur.FrameLoop

/**
 * JNI bridge to the demo's native lib (`libtur_demo.so`, built from
 * `demo/compose/native`).
 *
 * This is the app's own glue: it loads the `.so` and declares the
 * `createEngine` entry point that builds a tur engine with the **demo's**
 * plugin set (Std + Animation + Clipboard + Net + DemoHelper). The standard
 * engine-op symbols (`Java_org_tur_TurNative_*` — pump / input / IME / …) come
 * from the same `.so` (generated by `tur_android::standard_jni_exports!`) and
 * are resolved by the Kotlin lib's `org.tur.TurNative`; this object only owns
 * creation.
 *
 * The returned `Long` is an opaque engine handle, passed straight to
 * `TurView` via `TurEngineFactory` (see [MainActivity]).
 */
object DemoNative {
    init {
        System.loadLibrary("tur_demo")
    }

    /**
     * Build the engine over [surface] with the demo plugins. Returns an opaque
     * handle (`0` on failure — a `RuntimeException` is also thrown from native).
     */
    external fun createEngine(
        context: Context,
        surface: Surface,
        width: Int,
        height: Int,
        dpr: Double,
        frameLoop: FrameLoop,
    ): Long
}
