package org.tur.demo

import android.content.Context
import org.tur.FrameLoop

/**
 * JNI bridge to the demo's native lib (`libtur_demo.so`, built from
 * `demo/compose/native`).
 *
 * This is the app's own glue: it loads the `.so` and declares the
 * `createRuntime` entry point that builds a tur runtime with the **demo's**
 * plugin set (Std + Animation + Clipboard + Net + DemoHelper). The standard
 * engine-op symbols (`Java_org_tur_TurNative_*` — createInstance / pump / input
 * / IME / …) come from the same `.so` (generated by
 * `tur_android::standard_jni_exports!`) and are resolved by the Kotlin lib's
 * `org.tur.TurNative`; this object only owns runtime creation.
 *
 * The returned `Long` is an opaque runtime handle, passed to
 * [org.tur.TurRuntime] (see [MainActivity]).
 */
object DemoNative {
    init {
        System.loadLibrary("tur_demo")
    }

    /**
     * Build the shared runtime with the demo plugins. Returns an opaque runtime
     * handle (`0` on failure — a `RuntimeException` is also thrown from native).
     * No surface — instances are attached separately via `TurNative.createInstance`.
     */
    external fun createRuntime(context: Context): Long
}
