// Generates `cases_gen.rut` — the playground's case registry as a rut
// module fragment: `pg_case_count()`, `pg_case_name(i)`, and
// `pg_case_source(name)` over the embedded sources. Concatenated after
// `playground.rut` by the website's `playgroundSource()` (the two halves
// compile as ONE module), so the playground sidebar lists the curated
// showcase without any fetch/host I/O.
//
// The registry lists ONLY the curated showcase: the `showcase.json`
// manifest (the boa whitelist; display order = alphabetical, the same
// `.sort()` the boa reference applies). Corpus cases outside the manifest
// stay in the engine test corpus (`load_rut_bundle` covers all of them
// natively) but do not appear in the playground sidebar.
//
// Whitelist names deliberately absent from the manifest:
// - `github-viewer` / `text-demo` — pending their rut ports (the plan's
//   case-port phase); the manifest grows when they land.
// - `composited-transform-anchor-playground` — removed from the corpus in
//   b3d66d1 (a JS-rail-only demo; no rut port exists or is planned).
const fs = require("node:fs");
const path = require("node:path");

const workspaceRoot = path.resolve(__dirname, "..", "..", "..");
const engineCasesDir = path.join(workspaceRoot, "js", "packages", "tur-test-cases", "cases");
const manifestFile = path.resolve(__dirname, "..", "showcase.json");
const outFile = path.resolve(__dirname, "..", "cases_gen.rut");

const manifest = JSON.parse(fs.readFileSync(manifestFile, "utf8"));
if (!Array.isArray(manifest) || manifest.some((n) => typeof n !== "string" || n === "")) {
    console.error(`${path.relative(workspaceRoot, manifestFile)} must be a JSON array of case names`);
    process.exit(1);
}
if (new Set(manifest).size !== manifest.length) {
    console.error(`${path.relative(workspaceRoot, manifestFile)} has duplicate names`);
    process.exit(1);
}

const cases = [];
for (const name of [...manifest].sort()) {
    const indexFile = path.join(engineCasesDir, name, "index.rut");
    if (!fs.existsSync(indexFile)) {
        console.error(
            `showcase case \`${name}\` has no ${path.relative(workspaceRoot, indexFile)}` +
                " — remove it from showcase.json or port the case",
        );
        process.exit(1);
    }
    cases.push({ name, source: fs.readFileSync(indexFile, "utf8") });
}

const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");

const nameArms = cases
    .map((c, i) => `    if (i == ${i}) {\n        return "${esc(c.name)}";\n    }`)
    .join("\n");
const sourceArms = cases
    .map((c) => `    if (name == "${esc(c.name)}") {\n        return "${esc(c.source)}";\n    }`)
    .join("\n");

const code = `// AUTO-GENERATED by scripts/gen-cases.cjs — do not edit.
// The playground's case registry: one entry per showcase.json manifest
// name (js/packages/tur-test-cases/cases/<name>/index.rut), alphabetical.

fn pg_case_count() -> u64 {
    return ${cases.length};
}

fn pg_case_name(i: u64) -> str {
${nameArms}
    return "";
}

fn pg_case_source(name: str) -> str {
${sourceArms}
    return "";
}
`;

fs.writeFileSync(outFile, code);
console.log(`generated cases_gen.rut with ${cases.length} cases`);
