// Generates `src/cases/generated.ts` — inlines every case source as a files map
// so the self-hosted playground (@tur-ng/playground-view) has all case sources
// in-memory without any fetch/host I/O. Run via `pnpm gen-cases` or the
// prebuild step.
//
// Sources cases from TWO directories (merged):
//   1. The shared engine test cases (`js/packages/tur-test-cases/cases`) —
//      pure `tur:*`-only cases.
//   2. This package's own `cases/` dir — playground-only cases that also use
//      `tur-ext/demo-helper` (compiler-bridge-demo, github-viewer).
//
// Shape: `Record<string, Record<string, string>>` — case name → { filename → source }.
// Single-file cases store just `{ "index.ts": "..." }`; multi-file cases store
// all `*.ts` files found in the case directory.
const fs = require("node:fs");
const path = require("node:path");

const workspaceRoot = path.resolve(__dirname, "..", "..", "..");
const engineCasesDir = path.join(
    workspaceRoot,
    "js",
    "packages",
    "tur-test-cases",
    "cases",
);
const localCasesDir = path.resolve(__dirname, "..", "cases");
const outDir = path.resolve(__dirname, "..", "src", "cases");
fs.mkdirSync(outDir, { recursive: true });

/** Collect case entries (name → { filename → source }) from a cases dir. */
function collectFrom(casesDir, { embed } = { embed: false }) {
    const out = [];
    if (!fs.existsSync(casesDir)) return out;
    for (const name of fs.readdirSync(casesDir).sort()) {
        const caseDir = path.join(casesDir, name);
        if (!fs.statSync(caseDir).isDirectory()) continue;
        const indexFile = path.join(caseDir, "index.ts");
        if (!fs.existsSync(indexFile)) continue;

        // Collect all .ts files in the case directory (non-recursive for MVP;
        // sub-directories could be added later if needed).
        const files = fs
            .readdirSync(caseDir)
            .filter((f) => f.endsWith(".ts"))
            .sort();
        const fileMap = files.map((f) => {
            let src = fs.readFileSync(path.join(caseDir, f), "utf8");
            if (embed) src = embedTransform(src);
            return `${JSON.stringify(f)}: ${JSON.stringify(src)}`;
        });
        out.push(
            `    ${JSON.stringify(name)}: {\n${fileMap.map((s) => `        ${s}`).join(",\n")},\n    }`,
        );
    }
    return out;
}

// The shared engine cases are written to be ROOT-MOUNTED (their dist wrapper
// does `mount(store, Case)` with the case's own `export const store`). Their
// view/logic code is ctx-only — all reactive reads/writes flow through the
// closure ctx of `derive`/`mutate`, which the engine binds to the MOUNTED
// store. The module store object serves only the wrapper's `mount` and the
// Rust-test `globalThis.__*` hooks (which are inert here).
//
// So embedding needs exactly ONE rewrite: drop the `export` keyword from the
// store declaration. The embedded copy keeps an inert store (nothing view-
// reactive touches it), and every ctx closure resolves against the HOST's
// mounted store — the same atoms the tree reads.
function embedTransform(src) {
    return src.replace(
        /export const store = createStore\(\);/,
        "const store = createStore();",
    );
}

// Local (playground-only) cases take precedence on name collisions; otherwise
// the order just affects stable output ordering (each set is pre-sorted).
// Engine cases are embedded (root-mount source → de-export the store line);
// local playground cases are written embedding-aware already (ctx-only).
const entries = [
    ...collectFrom(engineCasesDir, { embed: true }),
    ...collectFrom(localCasesDir),
];

const code = `// AUTO-GENERATED by scripts/gen-cases.cjs — do not edit.

/** Case sources: case name → { filename → source }.
 *  Single-file cases have only "index.ts". */
export const CASE_SOURCES: Record<string, Record<string, string>> = {
${entries.join(",\n")},
};
`;
fs.writeFileSync(path.join(outDir, "generated.ts"), code);
console.log(`generated ${entries.length} case sources`);
