[package]
name = "tur"
description = "Facade crate combining tur-widget, tur-layout, tur-render-tree, tur-vello-renderer, tur-noop-renderer, and tur-boajs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tur-shared = { workspace = true }
tur-widget = { workspace = true }
tur-layout = { workspace = true }
tur-render-tree = { workspace = true }
tur-vello-renderer = { workspace = true }
tur-noop-renderer = { workspace = true }
tur-boajs = { workspace = true }
boa_engine = { workspace = true }
vello = { workspace = true }
winit = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
