[package]
name = "tur-element-tree"
description = "Element tree for tur (element nodes, tree structure, Element trait)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tur-trait = { workspace = true }
tur-render-tree = { workspace = true }
