// Generates `src/cases-generated.ts` — inlines every edgy-case source as a
// string so the self-hosted playground (tur-demo-impl) has all case sources
// in-memory without any fetch/host I/O. Run via `pnpm gen-cases` or the
// prebuild step.
const fs = require("node:fs");
const path = require("node:path");

const casesDir = path.resolve(
    __dirname,
    "..",
    "..",
    "tur-test-cases",
    "edgy-cases",
);
const outDir = path.resolve(__dirname, "..", "src");
fs.mkdirSync(outDir, { recursive: true });

const entries = [];
for (const name of fs.readdirSync(casesDir).sort()) {
    const file = path.join(casesDir, name, "index.ts");
    if (!fs.existsSync(file)) continue;
    const src = fs.readFileSync(file, "utf8");
    entries.push(`    ${JSON.stringify(name)}: ${JSON.stringify(src)}`);
}

const code = `// AUTO-GENERATED by scripts/gen-cases.cjs — do not edit.
export const CASE_SOURCES: Record<string, string> = {
${entries.join(",\n")},
};
`;
fs.writeFileSync(path.join(outDir, "cases-generated.ts"), code);
console.log(`generated ${entries.length} case sources`);
