// Generates `src/cases/generated.ts` — inlines every edgy-case source as a
// files map so the self-hosted playground (tur-demo-impl) has all case sources
// in-memory without any fetch/host I/O. Run via `pnpm gen-cases` or the
// prebuild step.
//
// Shape: `Record<string, Record<string, string>>` — case name → { filename → source }.
// Single-file cases store just `{ "index.ts": "..." }`; multi-file cases store
// all `*.ts` files found in the case directory.
const fs = require("node:fs");
const path = require("node:path");

const casesDir = path.resolve(
    __dirname,
    "..",
    "..",
    "tur-test-cases",
    "edgy-cases",
);
const outDir = path.resolve(__dirname, "..", "src", "cases");
fs.mkdirSync(outDir, { recursive: true });

const entries = [];
for (const name of fs.readdirSync(casesDir).sort()) {
    const caseDir = path.join(casesDir, name);
    if (!fs.statSync(caseDir).isDirectory()) continue;
    const indexFile = path.join(caseDir, "index.ts");
    if (!fs.existsSync(indexFile)) continue;

    // Collect all .ts files in the case directory (non-recursive for MVP;
    // sub-directories could be added later if needed).
    const files = fs
        .readdirSync(caseDir)
        .filter((f) => f.endsWith(".ts"))
        .sort();
    const fileMap = files.map((f) => {
        const src = fs.readFileSync(path.join(caseDir, f), "utf8");
        return `${JSON.stringify(f)}: ${JSON.stringify(src)}`;
    });
    entries.push(
        `    ${JSON.stringify(name)}: {\n${fileMap.map((s) => `        ${s}`).join(",\n")},\n    }`,
    );
}

const code = `// AUTO-GENERATED by scripts/gen-cases.cjs — do not edit.

/** Case sources: case name → { filename → source }.
 *  Single-file cases have only "index.ts". */
export const CASE_SOURCES: Record<string, Record<string, string>> = {
${entries.join(",\n")},
};
`;
fs.writeFileSync(path.join(outDir, "generated.ts"), code);
console.log(`generated ${entries.length} case sources`);
