//! The layering law — the phase-6 gate, pinned as a source-scan test.
//!
//! `core/` is MECHANISM ONLY: it must never reference `builtin_plugins`
//! (element/view types live in the plugins), and the shared builder
//! contract must never reappear (no `RutBuilder` trait, no generic
//! `el_build` / `el_child` / `el_qkey` / `el_vqkey` rows outside the
//! plugins — every family owns its spec + rows + its own `*_build`).

use std::path::{Path, PathBuf};

fn workspace_root() -> PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    Path::new(&manifest_dir)
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root")
        .to_path_buf()
}

fn collect_rs(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_rs(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}

/// Collect the rut-bearing text sources under `dir`: `.rut` packages and
/// `.rs` sources (the test corpora embed rut snippets in const strings —
/// the scans see them). Build outputs (`target/`) are skipped.
fn collect_rut_sources(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|n| n == "target") {
                continue;
            }
            collect_rut_sources(&path, out);
        } else if path
            .extension()
            .is_some_and(|e| e == "rs" || e == "rut")
        {
            out.push(path);
        }
    }
}

/// A line's code text: full-line comments (`// …`) are prose, not spellings
/// — the scan sees only lines that START with code.
fn code_line(line: &str) -> bool {
    !line.trim_start().starts_with("//")
}

/// The surface law's explicit exceptions — `(path suffix, reason)`. The
/// list is the documented accommodation surface: keep it MINIMAL so
/// anything NEW trips; adding an entry is a deliberate, commented
/// decision (each names the rail it keeps raw and why).
const TUR_HOST_IMPORT_EXCEPTIONS: &[(&str, &str)] = &[
    // The kits — the sanctioned surface (the law's whole point is that
    // tur_host rows are reachable ONLY through them).
    ("rut/tur_kit/", "the kit — the sanctioned tur_host surface"),
    (
        "rut/tur_anim_kit/",
        "the animation kit — plugin-owned prelude",
    ),
    ("rut/tur_net_kit/", "the net kit — plugin-owned prelude"),
    // The playground's documented upstream-workaround lines: the pg_* rows
    // (no kit — a 7th prelude pkg trips the layering law), the status
    // label's raw `rs_derive`, and the load-bearing second `use tur_host`
    // line (the duplicate-boot-scope interning bug).
    (
        "rut/playground/mod.rut",
        "the playground: pg_* rows + the status label's rs_derive + the \
         load-bearing second use line (upstream interning bug)",
    ),
    // GENERATED by scripts/gen-cases.cjs — embeds the case sources
    // verbatim (their use lines ride along).
    (
        "rut/playground/cases_gen.rut",
        "generated case registry — embeds case sources verbatim",
    ),
    // The one corpus case that imports tur_host: importing tur_net_kit
    // instead trips the upstream duplicate-boot-scope interning bug in
    // this large module (documented at the import; migrate at the next
    // rut bump — the tur_net_kit::net_request wrapper exists).
    (
        "rut/cases/github-viewer/mod.rut",
        "the net row stays raw: the tur_net_kit import trips the upstream \
         interning bug in this module (see the import note)",
    ),
    // ---- the test corpora's deliberate raw-row probes ----
    // (the thin-faithful-delegate law: a fixture keeps probing the rail
    // it means to probe; every entry names that rail)
    (
        "tests/rut_boot.rs",
        "raw-row probes: the rs_* structured-value rail, tctrl_paste/select/\
         text, focus_request, task_cancel, decode_utf8, clipboard rows",
    ),
    (
        "tests/rut_mutation_rail.rs",
        "the async capability rows (clipboard_read/write) probed raw",
    ),
    (
        "tests/perf/scenes.rs",
        "raw-rail perf probes: rs_get/set/source_f64 + the tctrl_push_span \
         span lane",
    ),
    (
        "tests/event/scrollbar.rs",
        "the raw rs_source_f64 rail (offset injection) probed directly",
    ),
    (
        "tests/event/caret_into_view.rs",
        "the tctrl_push_span span lane probed raw",
    ),
    (
        "tests/event/editable_text.rs",
        "the tctrl_push_span span lane probed raw",
    ),
    (
        "tests/element/text_huge_document.rs",
        "the tctrl_push_span span lane probed raw",
    ),
    (
        "tests/element/rich_text_perf.rs",
        "the tctrl_push_span span lane probed raw",
    ),
    (
        "tests/element/encode.rs",
        "the bytes helpers (decode_utf8/encode_utf8) — no kit wrapper",
    ),
    (
        "tests/playground_viewer.rs",
        "the pg_* rows — deliberately kit-less (a 7th prelude pkg trips the \
         layering law)",
    ),
    (
        "tur-playground/src/highlight.rs",
        "a classification sample embeds a use line as highlighter input",
    ),
];

/// The `rs_derive` / `rs_derive2` / `rs_watch` rail's call-site exceptions
/// (the plain-fn derive lane + the click-shaped watch are kit-internal
/// since phase 4/5; definitions are skipped, not excepted).
const RAW_RAIL_CALL_EXCEPTIONS: &[(&str, &str)] = &[
    (
        "rut/tur_kit/reactive/",
        "the wrappers' home (the sanctioned plain-fn rail)",
    ),
    (
        "rut/playground/mod.rut",
        "the status label (the documented upstream workaround)",
    ),
    (
        "tests/perf/scenes.rs",
        "the perf scene's plain-fn derive (kit-spelled, same accommodation)",
    ),
];

#[test]
fn core_is_mechanism_only() {
    let core = workspace_root().join("libs/tur-engine/src/core");
    let mut files = Vec::new();
    collect_rs(&core, &mut files);
    assert!(
        files.len() > 50,
        "core source scan found {} files — the walker is broken",
        files.len()
    );

    let mut violations = Vec::new();
    for file in files {
        let Ok(src) = std::fs::read_to_string(&file) else {
            continue;
        };
        for (line_no, line) in src.lines().enumerate() {
            if line.contains("builtin_plugins") {
                violations.push(format!(
                    "{}:{}: core references builtin_plugins: {}",
                    file.display(),
                    line_no + 1,
                    line.trim()
                ));
            }
        }
    }
    assert!(
        violations.is_empty(),
        "the layering law: core must own mechanism, never elements —\n{}",
        violations.join("\n")
    );
}

#[test]
fn no_shared_builder_contract() {
    // The shared builder contract is gone: every element family owns its
    // spec + rows + its own `*_build` terminal. The generic rows and the
    // `RutBuilder`-style trait must never reappear outside the plugins
    // (the kit wraps family rows; core knows nothing of builders).
    let engine = workspace_root().join("libs/tur-engine/src");
    let mut files = Vec::new();
    collect_rs(&engine, &mut files);

    let forbidden = ["el_build(", "el_child(", "el_qkey(", "el_vqkey("];
    let mut violations = Vec::new();
    for file in files {
        let Ok(src) = std::fs::read_to_string(&file) else {
            continue;
        };
        for (line_no, line) in src.lines().enumerate() {
            // `RutBuilder` anywhere is a violation.
            if line.contains("RutBuilder") {
                violations.push(format!(
                    "{}:{}: a shared RutBuilder contract reappeared: {}",
                    file.display(),
                    line_no + 1,
                    line.trim()
                ));
            }
            for row in forbidden {
                if line.contains(row) {
                    violations.push(format!(
                        "{}:{}: the generic `{}` row reappeared: {}",
                        file.display(),
                        line_no + 1,
                        row.trim_end_matches('('),
                        line.trim()
                    ));
                }
            }
        }
    }
    assert!(
        violations.is_empty(),
        "the layering law: every family owns its rows; no shared builder \
         contract may reappear —\n{}",
        violations.join("\n")
    );
}

/// The `tur_host` exposure law: the host pkg is reachable ONLY through the
/// kits (`rut/tur_kit` / `tur_anim_kit` / `tur_net_kit`). Scans every
/// `.rut` source and every `.rs` source (inline snippets included) under
/// `rut/`, `libs/`, and `demo/`; the documented exceptions live in
/// [`TUR_HOST_IMPORT_EXCEPTIONS`].
#[test]
fn tur_host_is_kits_only() {
    let root = workspace_root();
    let mut files = Vec::new();
    for dir in ["rut", "libs", "demo"] {
        collect_rut_sources(&root.join(dir), &mut files);
    }
    assert!(
        files.len() > 300,
        "the surface scan found {} files — the walker is broken",
        files.len()
    );

    let mut violations = Vec::new();
    for file in files {
        let rel = file
            .strip_prefix(&root)
            .unwrap_or(&file)
            .to_string_lossy()
            .to_string();
        if rel.ends_with("tests/layering.rs")
            || TUR_HOST_IMPORT_EXCEPTIONS.iter().any(|(s, _)| rel.contains(s))
        {
            // The law's own source names the spellings it bans.
            continue;
        }
        let Ok(src) = std::fs::read_to_string(&file) else {
            continue;
        };
        for (line_no, line) in src.lines().enumerate() {
            if code_line(line) && line.contains("use tur_host") {
                violations.push(format!(
                    "{}:{}: tur_host is kits-only (see TUR_HOST_IMPORT_EXCEPTIONS): {}",
                    rel,
                    line_no + 1,
                    line.trim()
                ));
            }
        }
    }
    assert!(
        violations.is_empty(),
        "the surface law: `use tur_host` outside the kits —\n{}",
        violations.join("\n")
    );
}

/// The raw-rail law: `rs_derive` / `rs_derive2` / `rs_watch` never appear
/// at CALL sites — the kit's typed surface (`derive<T>` / `watch<T>`) is
/// the authored spelling; the plain-fn wrappers live kit-internally
/// (definitions are skipped). The playground's status label and the perf
/// scene ride the documented upstream accommodations.
#[test]
fn raw_reactive_rail_has_no_call_sites() {
    let root = workspace_root();
    let mut files = Vec::new();
    for dir in ["rut", "libs", "demo"] {
        collect_rut_sources(&root.join(dir), &mut files);
    }

    let mut violations = Vec::new();
    for file in files {
        let rel = file
            .strip_prefix(&root)
            .unwrap_or(&file)
            .to_string_lossy()
            .to_string();
        if rel.ends_with("tests/layering.rs")
            || RAW_RAIL_CALL_EXCEPTIONS.iter().any(|(s, _)| rel.contains(s))
        {
            continue;
        }
        let Ok(src) = std::fs::read_to_string(&file) else {
            continue;
        };
        for (line_no, line) in src.lines().enumerate() {
            if !code_line(line) {
                continue;
            }
            let t = line.trim();
            // A definition line (`pub fn rs_derive(` / `fn rs_watch(`) is
            // the wrapper's home, not a call site.
            if t.contains("fn rs_derive(") || t.contains("fn rs_derive2(") || t.contains("fn rs_watch(")
            {
                continue;
            }
            if t.contains("rs_derive(") || t.contains("rs_derive2(") || t.contains("rs_watch(") {
                violations.push(format!(
                    "{}:{}: the raw reactive rail has no call sites (use the \
                     kit's derive<T>/watch<T>): {}",
                    rel,
                    line_no + 1,
                    t
                ));
            }
        }
    }
    assert!(
        violations.is_empty(),
        "the raw-rail law: rs_derive/rs_derive2/rs_watch at a call site —\n{}",
        violations.join("\n")
    );
}

/// The stash law: `st_put` / `st_take` / `stf_put` / `stf_take` are
/// DELETED rows (phase 5) — zero spellings anywhere, in any `.rut` source
/// or `.rs` inline snippet. The compiler enforces the rows' absence; this
/// scan pins that the spellings never reintroduce (a re-added row would
/// fail here before it gains a user).
#[test]
fn stash_spellings_are_gone() {
    let root = workspace_root();
    let mut files = Vec::new();
    for dir in ["rut", "libs", "demo"] {
        collect_rut_sources(&root.join(dir), &mut files);
    }
    assert!(
        files.len() > 300,
        "the stash scan found {} files — the walker is broken",
        files.len()
    );

    let spellings = ["st_put", "st_take", "stf_put", "stf_take"];
    let mut violations = Vec::new();
    for file in files {
        let rel = file
            .strip_prefix(&root)
            .unwrap_or(&file)
            .to_string_lossy()
            .to_string();
        if rel.ends_with("tests/layering.rs") {
            // The law's own source names the spellings it bans.
            continue;
        }
        let Ok(src) = std::fs::read_to_string(&file) else {
            continue;
        };
        for (line_no, line) in src.lines().enumerate() {
            for s in spellings {
                if line.contains(s) {
                    violations.push(format!(
                        "{}:{}: the stash row `{s}` is deleted — zero spellings \
                         anywhere: {}",
                        rel,
                        line_no + 1,
                        line.trim()
                    ));
                }
            }
        }
    }
    assert!(
        violations.is_empty(),
        "the stash law: st_*/stf_* spellings reappeared —\n{}",
        violations.join("\n")
    );
}
