//! The corpus compile gate: every rut case in
//! `rut/cases` must compile against the standard
//! plugin set (the callback rail's corpus-wide pin — a case that
//! regressions to a stringly-typed callback or a stale row name fails
//! here, per case, with its own load error), and every case directory
//! must carry its GENERATED `rut.jsonc` manifest (name + entry + the
//! tur_kit dep) — the manifest grammar lives upstream
//! (`rut_driver::parse_manifest`); the generator is this test's bless
//! mode, so the manifests are an artifact, never hand-edited prose.

use std::path::Path;
use std::time::Duration;

use rut_driver::bundle::parse_manifest;
use tur_integration_tests::TurTestApp;

fn workspace_root() -> std::path::PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    Path::new(&manifest_dir)
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root")
        .to_path_buf()
}

/// The generated per-case manifest — deterministic text, byte-pinned (the
/// shape the loader + the editor dep-walk read: `entry.lib` = the case's
/// index, `deps` = the kit at its sibling path). The manifest `name` is a
/// USE-PATH name — the grammar allows bare `[a-zA-Z0-9_]+` only — so a
/// kebab-case dir name sanitizes to underscores (the name is nominal for
/// a leaf case; nothing imports it).
fn case_manifest_text(dir_name: &str) -> String {
    let name = dir_name.replace('-', "_");
    format!(
        "// GENERATED by the case-manifest generator (the corpus gate's \
         bless mode:\n// TUR_BLESS_CASE_MANIFESTS=1 cargo nextest run -p \
         tur-integration-tests\n// every_corpus_case) — regenerate, never \
         hand-edit. The name is the grammar's\n// bare form of the dir name \
         (kebab -> underscores; nominal for a leaf case).\n{{\n  \"name\": \
         \"{name}\",\n  \"entry\": {{ \"lib\": \"./index.rut\" }},\n  \
         \"deps\": {{ \"tur_kit\": {{ \"path\": \"../../tur_kit\" }} }}\n}}\n"
    )
}

#[test]
fn every_corpus_case_has_a_manifest_and_compiles_against_the_standard_kit() {
    let cases_dir = workspace_root().join("rut/cases");
    let mut names: Vec<String> = std::fs::read_dir(&cases_dir)
        .expect("cases dir")
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .filter(|n| cases_dir.join(n).join("index.rut").exists())
        .collect();
    names.sort();

    assert!(
        names.len() >= 100,
        "the corpus should sweep every case, found {}",
        names.len()
    );

    // The manifests: every case dir carries its generated rut.jsonc (a
    // stale or missing one fails here; bless mode rewrites the set).
    let bless = std::env::var("TUR_BLESS_CASE_MANIFESTS").is_ok();
    let mut manifest_failures = Vec::new();
    for name in &names {
        let manifest_path = cases_dir.join(name).join("rut.jsonc");
        let expected = case_manifest_text(name);
        if bless {
            std::fs::write(&manifest_path, &expected).expect("bless: write the manifest");
            continue;
        }
        match std::fs::read_to_string(&manifest_path) {
            Ok(text) if text == expected => {}
            Ok(_) => manifest_failures.push(format!(
                "{name}: rut.jsonc drifted from the generated text (bless to \
                 regenerate)"
            )),
            Err(_) => manifest_failures.push(format!(
                "{name}: no rut.jsonc (bless mode generates the set)"
            )),
        }
    }
    if bless {
        eprintln!("blessed {} case manifests", names.len());
        return;
    }
    assert!(
        manifest_failures.is_empty(),
        "{} case manifest(s) failed:\n{}",
        manifest_failures.len(),
        manifest_failures.join("\n")
    );

    // The manifests parse under the loader's grammar and say what the
    // generator says (the bare-form name; the kit dep).
    for name in &names {
        let text =
            std::fs::read_to_string(cases_dir.join(name).join("rut.jsonc")).unwrap();
        let m = parse_manifest(&text)
            .unwrap_or_else(|e| panic!("{name}: rut.jsonc does not parse: {e}"));
        assert_eq!(
            m.name.as_deref(),
            Some(name.replace('-', "_").as_str()),
            "{name}: manifest name (the dir's bare form)"
        );
        assert_eq!(
            m.entry.lib.as_deref(),
            Some("./index.rut"),
            "{name}: manifest entry"
        );
        assert!(
            m.deps.contains_key("tur_kit"),
            "{name}: the manifest deps carry the kit"
        );
    }

    // The compile sweep (the browser-shaped capability set: showcase cases
    // ride the net rows — github-viewer — which only install when Http is
    // present).
    let mut failures = Vec::new();
    for name in &names {
        let source = std::fs::read_to_string(cases_dir.join(name).join("index.rut")).unwrap();
        let app = TurTestApp::new_with_http(400.0, 600.0).unwrap();
        if let Err(e) = app.load_rut_module(&source) {
            failures.push(format!("{name}: {e}"));
        } else {
            app.wait_for_timeout(Duration::ZERO);
        }
    }
    assert!(
        failures.is_empty(),
        "{} corpus case(s) failed to compile:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
