[package]
name = "tur-vello-renderer"
description = "Vello rendering backend for tur widgets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tur-widget = { workspace = true }
vello = { workspace = true }
raw-window-handle = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
