[package]
name = "tur-wasm"
description = "WebAssembly binary for tur rendering engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tur-engine = { workspace = true, features = ["webgl"] }
tur-std = { workspace = true }
tur-clipboard = { workspace = true }
tur-net = { workspace = true }
tur-shared = { workspace = true }
boa_engine = { workspace = true, features = ["js"] }
tracing = { workspace = true }
tracing-wasm = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "HtmlTextAreaElement",
    "Node",
    "EventTarget",
    "Event",
    "MouseEvent",
    "KeyboardEvent",
    "CompositionEvent",
    "FocusEvent",
    "CssStyleDeclaration",
    "DomRect",
    "DomRectReadOnly",
    "WheelEvent",
    "TouchEvent",
    "Touch",
    "TouchList",
    "Navigator",
    "Clipboard",
    "ClipboardEvent",
    "DataTransfer",
    "Blob",
    "BlobPropertyBag",
    "File",
    "FileList",
    "HtmlInputElement",
    "HtmlAnchorElement",
    "ResizeObserver",
    "Url",
] }
js-sys = "0.3"
console_error_panic_hook = { workspace = true }
getrandom = { workspace = true, features = ["wasm_js"] }
wasm-bindgen-futures = { workspace = true }
reqwest-wasm = { version = "0.11", default-features = false }
swc_common = "23.0.1"
swc_ecma_ast = "25.0.0"
swc_ecma_visit = "25.0.0"
swc_ecma_parser = { version = "41.1.0", features = ["typescript", "unstable"] }
swc_ecma_transforms_base = "44.0.2"
swc_ecma_transforms_typescript = "49.0.0"
swc_ecma_codegen = "28.0.1"
