name: Local CI

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  SCCACHE_CACHE_SIZE: 2G

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone git@github.com:hpp2334/tur.git .
          git checkout ${{ env.BRANCH_NAME }}

      - name: Check merge conflict
        run: |
          git fetch origin main
          BASE=$(git merge-base HEAD origin/main)
          git merge-tree $BASE origin/main HEAD

      - name: Install JS deps
        run: pnpm install --frozen-lockfile
        working-directory: ./js

      - name: Build JS
        run: pnpm build
        working-directory: ./js

      - name: Install cargo-nextest
        run: |
          command -v cargo-nextest >/dev/null || {
            curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
          }
          cargo nextest --version

      - name: Cargo test
        run: xvfb-run -a cargo nextest run --workspace --locked --profile ci
        timeout-minutes: 5
        env:
          RUST_MIN_STACK: 8388608

      - name: Cargo doc test
        run: cargo test --workspace --doc --locked
        timeout-minutes: 5
        env:
          RUST_MIN_STACK: 8388608

      - name: Cargo clippy
        run: cargo clippy --workspace --locked -- -D warnings

      - name: Typecheck JS
        run: pnpm typecheck
        working-directory: ./js

      - name: Check JS
        run: pnpm check
        working-directory: ./js

      - name: wasm-pack build
        run: wasm-pack build --target web --no-opt -- --locked
        working-directory: ./demo/website/native
